# Book settings
title: Neurocomputing
author: Julien Vitay
logo: img/tuc.svg

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Information about where the book exists on the web
repository:
  url                       : https://github.com/vitay/lecturenotes-neurocomputing  # Online location of your book
  path_to_book              : neurocomputing  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"