# Book settings
title: Neurocomputing
author: Julien Vitay
logo: img/tuc.svg

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js